//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControleNotasXProva
    {
        public int idControleNotas { get; set; }
        public int idProva { get; set; }
        public Nullable<int> numAcertos { get; set; }
    
        public virtual ControleNotas ControleNotas { get; set; }
        public virtual Prova Prova { get; set; }
    }
}
