//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControleNotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControleNotas()
        {
            this.AvaliacaoTutoria = new HashSet<AvaliacaoTutoria>();
            this.ControleNotasXProva = new HashSet<ControleNotasXProva>();
            this.ControleNotasXAula = new HashSet<ControleNotasXAula>();
        }
    
        public int idControleNotas { get; set; }
        public Nullable<int> idInscricaoTurma { get; set; }
        public Nullable<int> idModulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoTutoria> AvaliacaoTutoria { get; set; }
        public virtual InscricaoTurma InscricaoTurma { get; set; }
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControleNotasXProva> ControleNotasXProva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControleNotasXAula> ControleNotasXAula { get; set; }
    }
}
