//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaAvaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FichaAvaliacao()
        {
            this.PerguntaXFicha = new HashSet<PerguntaXFicha>();
        }
    
        public int idAvaliador { get; set; }
        public int idAvaliacaoTutoria { get; set; }
        public int idFichaAvaliacao { get; set; }
    
        public virtual AvaliacaoTutoria AvaliacaoTutoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerguntaXFicha> PerguntaXFicha { get; set; }
    }
}
