//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.InscricaoTurma = new HashSet<InscricaoTurma>();
            this.AvaliacaoTutoria = new HashSet<AvaliacaoTutoria>();
        }
    
        public int idGrupo { get; set; }
        public Nullable<int> idProfessor { get; set; }
        public int idMed { get; set; }
        public string descGrupo { get; set; }
        public bool ativo { get; set; }
    
        public virtual Med Med { get; set; }
        public virtual Professor Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscricaoTurma> InscricaoTurma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoTutoria> AvaliacaoTutoria { get; set; }
    }
}
