//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerguntaXFicha
    {
        public int idPergunta { get; set; }
        public int idFichaAvaliacao { get; set; }
        public Nullable<bool> marcado { get; set; }
    
        public virtual FichaAvaliacao FichaAvaliacao { get; set; }
        public virtual Pergunta Pergunta { get; set; }
    }
}
